/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import infinitystore.com.LojaAdmin;
import infinitystore.com.Produto;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author marcio
 */
public class CadastrarProduto extends javax.swing.JFrame {
    private LojaAdmin admin = new LojaAdmin();
    /**
     * Creates new form CadastrarProduto
     */
    public CadastrarProduto() {
        admin.recuperaDados();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        marca = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        valor = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricao = new javax.swing.JTextArea();
        quantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        marca.setText("Marca");
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });
        getContentPane().add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 185, -1));

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        valor.setText("Valor");
        getContentPane().add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 80, -1));

        nome.setText("Nome");
        getContentPane().add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 185, -1));

        descricao.setBackground(new java.awt.Color(26, 26, 26));
        descricao.setColumns(20);
        descricao.setLineWrap(true);
        descricao.setRows(5);
        descricao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descricao);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 270, 90));

        quantidade.setText("Quantidade");
        getContentPane().add(quantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 100, -1));

        setSize(new java.awt.Dimension(564, 356));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String nomeProduto = nome.getText();
        String marcaProduto = marca.getText();
        String descricaoProduto = descricao.getText();
        try{
            int quant = Integer.parseInt(quantidade.getText());
            double valorProduto = Double.parseDouble(valor.getText());
            if(!nomeProduto.equals("") && !marcaProduto.equals("")){   
                Produto produto = new Produto(nomeProduto, marcaProduto, descricaoProduto, quant, "", valorProduto);
                String status = admin.addProduto(produto);
                admin.gravaDados();
                String mensagem = String.format(" no valor de R$ %.2f", valorProduto);
                JOptionPane.showMessageDialog(null, "Produto " + status + mensagem + "."); 
            } else{
                JOptionPane.showMessageDialog(null, "Dados inválidos!");
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Valor inválido!");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descricao;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
